server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
    alibaba:
      seata:
        tx-service-group: gmall_tx_group
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.227.128
  elasticsearch:
    rest:
      uris:  http://192.168.227.128:9200
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.227.128
    virtual-host: /fengge
    username: fengge
    password: fengge
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
        concurrency: 3
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: debug


