server:
  port: 18092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.227.128
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.227.128
    virtual-host: /fengge
    username: fengge
    password: fengge
feign:
  sentinel:
    enabled: true
#thread:
  #pool:
   # coreSize: 100
   # maxSize: 500
    #keepalive: 60
    #blockQueueSize: 1000